services:

  mysql:
    container_name: "mysql"
    hostname: "mysql"
    image: yobasystems/alpine-mariadb:latest
    restart: "always"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-mysql}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-employees}
      MYSQL_USER: ${MYSQL_USER:-mysql}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-mysql}
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
    volumes:
      - sql:/var/lib/mysql
      - ./sql/test_db:/tmp/test_db
      - ./cmd/mysql/001_load_employees.sh:/docker-entrypoint-initdb.d/001_load_employees.sh
      # - ./sql/test_db/employees.sql:/docker-entrypoint-initdb.d/employees.sql
      # - ./sql/test_db/load_departments.dump:/docker-entrypoint-initdb.d/load_departments.dump
      # - ./sql/test_db/load_employees.dump:/docker-entrypoint-initdb.d/load_employees.dump
      # - ./sql/test_db/load_dept_emp.dump:/docker-entrypoint-initdb.d/load_dept_emp.dump
      # - ./sql/test_db/load_dept_manager.dump:/docker-entrypoint-initdb.d/load_dept_manager.dump
      # - ./sql/test_db/load_titles.dump:/docker-entrypoint-initdb.d/load_titles.dump
      # - ./sql/test_db/load_salaries1.dump:/docker-entrypoint-initdb.d/load_salaries1.dump
      # - ./sql/test_db/load_salaries2.dump:/docker-entrypoint-initdb.d/load_salaries2.dump
      # - ./sql/test_db/load_salaries3.dump:/docker-entrypoint-initdb.d/load_salaries3.dump
      # - ./sql/test_db/show_elapsed.sql:/docker-entrypoint-initdb.d/show_elapsed.sql

  redis:
    container_name: "redis"
    hostname: "redis"
    image: redis:7.0.12-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning

  nginx:
    container_name: "nginx"
    hostname: "nginx"
    profiles: [ "application" ]
    image: nginx:1.21.6-alpine
    depends_on:
      - read
      - go-blog-cache-write
    restart: "always"
    ports:
      - "8080:80"
    volumes:
      - "./config/nginx.conf:/etc/nginx/conf.d/default.conf"

  read:
    hostname: "go-blog-cache-read"
    profiles: [ "application" ]
    image: ghcr.io/antonio-alexander/go-blog-cache:latest
    depends_on:
      - mysql
      - redis
    deploy:
      replicas: 2
    ports:
     - 8080
    restart: "always"
    build:
      context: ./
      dockerfile: ./cmd/service/Dockerfile
      args:
        PLATFORM: ${PLATFORM:-linux/amd64}
        GO_ARCH: ${GO_ARCH:-amd64}
        GO_ARM: ${GO_ARM:-7}
    environment:
      DATABASE_HOST: ${DATABASE_HOST:-mysql}
      DATABASE_PORT: ${DATABASE_PORT:-3306}
      DATABASE_NAME: ${DATABASE_NAME:-employees}
      DATABASE_USER: ${DATABASE_USER:-mysql}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-mysql}
      DATABASE_QUERY_TIMEOUT: ${DATABASE_QUERY_TIMEOUT:-10}
      SERVICE_ADDRESS: ${SERVICE_ADDRESS}
      SERVICE_PORT: "8080"
      SERVICE_SHUTDOWN_TIMEOUT: ${SERVICE_SHUTDOWN_TIMEOUT:-10}
      SERVICE_CORS_DISABLED: ${SERVICE_CORS_DISABLED}
      SERVICE_CORS_ALLOWED_ORIGINS: ${SERVICE_CORS_ALLOWED_ORIGINS:-*}
      SERVICE_CORS_ALLOWED_METHODS: ${SERVICE_CORS_ALLOWED_METHODS:-POST,PUT,GET,DELETE,PATCH}
      SERVICE_CORS_ALLOWED_HEADERS: ${SERVICE_CORS_ALLOWED_HEADERS:-Access-Control-Allow-Origin,Correlation-Id}
      SERVICE_CORS_DEBUG: ${SERVICE_CORS_DEBUG}
      DATABASE_PARSE_TIME: ${DATABASE_PARSE_TIME:-true}
      REDIS_ADDRESS: ${REDIS_ADDRESS:-redis}
      REDIS_PORT:    ${REDIS_PORT:-6379}
      MUTATE_DISABLED: ${MUTATE_DISABLED:-true}
      LOGGING_LEVEL: ${LOGGING_LEVEL}

  go-blog-cache-write:
    container_name: "go-blog-cache-write"
    hostname: "go-blog-cache-write"
    profiles: [ "application" ]
    image: ghcr.io/antonio-alexander/go-blog-cache:latest
    depends_on:
      - mysql
      - redis
    ports:
     - 8081:8080
    restart: "always"
    build:
      context: ./
      dockerfile: ./cmd/service/Dockerfile
      args:
        PLATFORM: ${PLATFORM:-linux/amd64}
        GO_ARCH: ${GO_ARCH:-amd64}
        GO_ARM: ${GO_ARM:-7}
    environment:
      DATABASE_HOST: ${DATABASE_HOST:-mysql}
      DATABASE_PORT: ${DATABASE_PORT:-3306}
      DATABASE_NAME: ${DATABASE_NAME:-employees}
      DATABASE_USER: ${DATABASE_USER:-mysql}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-mysql}
      DATABASE_QUERY_TIMEOUT: ${DATABASE_QUERY_TIMEOUT:-10}
      SERVICE_ADDRESS: ${SERVICE_ADDRESS}
      SERVICE_PORT: "8080"
      SERVICE_SHUTDOWN_TIMEOUT: ${SERVICE_SHUTDOWN_TIMEOUT:-10}
      SERVICE_CORS_DISABLED: ${SERVICE_CORS_DISABLED}
      SERVICE_CORS_ALLOWED_ORIGINS: ${SERVICE_CORS_ALLOWED_ORIGINS:-*}
      SERVICE_CORS_ALLOWED_HEADERS: ${SERVICE_CORS_ALLOWED_HEADERS:-Access-Control-Allow-Origin,Correlation-Id}
      SERVICE_CORS_ALLOWED_METHODS: ${SERVICE_CORS_ALLOWED_METHODS:-POST,PUT,GET,DELETE,PATCH}
      SERVICE_CORS_DEBUG: ${SERVICE_CORS_DEBUG}
      DATABASE_PARSE_TIME: ${DATABASE_PARSE_TIME:-true}
      REDIS_ADDRESS: ${REDIS_ADDRESS:-redis}
      REDIS_PORT:    ${REDIS_PORT:-6379}
      LOGGING_LEVEL: ${LOGGING_LEVEL}

volumes:
  sql: