package data

import (
	"encoding"
	"encoding/json"
	"errors"
	"net/http"
)

type ErrorType string

func (e ErrorType) StatusCode() int {
	switch e {
	default:
		return http.StatusInternalServerError
	case ErrorTypeNotFound, ErrorTypeNotCached:
		return http.StatusNotFound
	case ErrorTypeNotCachedRetry:
		return http.StatusTooManyRequests
	}
}

const (
	ErrorTypeUnknown        ErrorType = "ERR_UNKNOWN"
	ErrorTypeNotFound       ErrorType = "ERR_NOT_FOUND"
	ErrorTypeNotCached      ErrorType = "ERR_NOT_CACHED"
	ErrorTypeNotCachedRetry ErrorType = "ERR_NOT_CACHED_RETRY"
)

var (
	_ encoding.BinaryUnmarshaler = &Error{}
	_ encoding.BinaryMarshaler   = &Error{}
)

// Error represents any error that can be generated by bludgeon
// swagger:model Error
type Error struct {
	error

	// Type contains the text of the type of error
	// example: not found
	ErrorType `json:"error_type"`

	// Error contains the text of any failed operation
	// example: employee not found
	ErrorMessage string `json:"error_message"`
}

func (e *Error) UnmarshalBinary(bytes []byte) error {
	return json.Unmarshal(bytes, &e)
}

func (e *Error) MarshalBinary() ([]byte, error) {
	return json.Marshal(&e)
}

func (e *Error) Error() string {
	if e.error != nil {
		return e.error.Error()
	}
	return e.ErrorMessage
}

func (e *Error) Type() string {
	return string(e.ErrorType)
}

func (e *Error) Is(err error) bool {
	if err, ok := err.(interface {
		Type() string
	}); ok {
		return string(e.ErrorType) == err.Type()
	}
	return false
}

func NewError(err any, errorTypes ...ErrorType) error {
	errorType := ErrorTypeUnknown
	if len(errorTypes) > 0 {
		errorType = ErrorType(errorTypes[0])
	}
	switch err := err.(type) {
	default:
		return nil
	case error:
		return &Error{
			error:        err,
			ErrorMessage: err.Error(),
			ErrorType:    errorType,
		}
	case string:
		return &Error{
			error:        errors.New(err),
			ErrorMessage: err,
			ErrorType:    errorType,
		}
	}
}

var (
	ErrUnknown        error = &Error{ErrorType: ErrorTypeUnknown}
	ErrNotFound       error = &Error{ErrorType: ErrorTypeNotFound}
	ErrNotCached      error = &Error{ErrorType: ErrorTypeNotCached}
	ErrNotCachedRetry error = &Error{ErrorType: ErrorTypeNotCachedRetry}
)

func NewUnknownError(item any) error {
	return NewError(item, ErrorTypeUnknown)
}

func NewNotFoundError(item any) error {
	return NewError(item, ErrorTypeNotFound)
}

func NewNotCachedError(item any) error {
	return NewError(item, ErrorTypeNotCached)
}

func NewNotCachedRetryError(item any) error {
	return NewError(item, ErrorTypeNotCachedRetry)
}
